Models/TAIKHOAN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chothuexe1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.HOADONs = new HashSet<HOADON>();
            this.XETHUEs = new HashSet<XETHUE>();
        }
    
        public int MaTK { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên đăng nhập.")]
        public string TenDangNhap { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mật khẩu.")]
        public string MatKhau { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập họ và tên.")]
        public string HoVaTen { get; set; }

        [RegularExpression(@"^\d{9,12}$", ErrorMessage = "Số căn cước công dân phải có từ 9 đến 12 chữ số.")]
        public string CCCD { get; set; }

        [RegularExpression(@"^\d{10}$", ErrorMessage = "Số điện thoại phải có đúng 10 chữ số.")]
        public string SDT { get; set; }
        public string Email { get; set; }
        public string AnhDaiDien { get; set; }
        public int Quyen { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XETHUE> XETHUEs { get; set; }
    }
}

Controllers/TAIKHOANsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using chothuexe1.Models;

namespace chothuexe1.Controllers
{
    public class TAIKHOANsController : Controller
    {
        private DoAnPhanMemEntities db = new DoAnPhanMemEntities();

        // GET: TAIKHOANs
        public ActionResult Index()
        {
            return View(db.TAIKHOANs.ToList());
        }


        //Dang ky
        public ActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Signup(TAIKHOAN taikhoan)
        {
            if (ModelState.IsValid)
            {
                if (db.TAIKHOANs.Any(x => x.SDT == taikhoan.SDT))
                {
                    ModelState.AddModelError("SDT", "Số điện thoại đã tồn tại");
                }
                else if (db.TAIKHOANs.Any(x => x.CCCD == taikhoan.CCCD))
                {
                    ModelState.AddModelError("CCCD", "Số CCCD đã tồn tại");
                }
                else
                {
                    taikhoan.Quyen = 1;
                    taikhoan.TrangThai = true;
                    db.TAIKHOANs.Add(taikhoan);
                    db.SaveChanges();

                    Session["tendangnhap"] = taikhoan.TenDangNhap.ToString();
                    return RedirectToAction("Index", "Home");
                }
            }

            // Nếu ModelState không hợp lệ, trả về view với dữ liệu và lỗi.
            return View(taikhoan);
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(TAIKHOAN taikhoan)
        {
            var user = db.TAIKHOANs.Where(x => x.SDT.Equals(taikhoan.SDT) && x.MatKhau.Equals(taikhoan.MatKhau)).FirstOrDefault();
            if (user != null)
            {
                // Lưu họ và tên vào Session
                Session["HoTen"] = user.HoVaTen;
                Session["MaTK"] = user.MaTK;
                return RedirectToAction("Index", "Home");
            }

            else
            {
                ViewBag.Notification = "Sai số điện thoại hoặc mật khẩu";
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/TAIKHOANs/Login.cshtml
@model chothuexe1.Models.TAIKHOAN

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="~/fonts/css/styles.css" rel="stylesheet" />
</head>
<body>
    <div class="form">

        <div class="tab-content">
            <div id="login">
                <h1>Đăng Nhập</h1>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="field-wrap">
                        <label class="phone-label">
                            Số điện thoại<span class="req">*</span>
                        </label>
                        @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control", required = "required", autocomplete = "off" } })
                    </div>

                    <div class="field-wrap">
                        <label class="password-label">
                            Mật Khẩu<span class="req">*</span>
                        </label>
                        @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control", required = "required", autocomplete = "off", type = "password" } })
<<<<<<< Updated upstream
=======

>>>>>>> Stashed changes
                    </div>

                    <p class="forgot"><a href="#">Quên mật khẩu?</a></p>

                    <button class="button button-block" type="submit">Đăng Nhập</button>
                }

                <p>@Html.ActionLink("Bạn chưa có tài khoản ?Đăng ký", "Signup", "TAIKHOANs")</p>
                @* Display the error message directly on the page *@
                @if (ViewBag.Notification != null)
                {
<<<<<<< Updated upstream
                     <p class="error-message" style="color: red;">@ViewBag.Notification</p>
=======
                    <p class="error-message1" style="color: red;">@ViewBag.Notification</p>
>>>>>>> Stashed changes
                }
            </div>


        </div><!-- tab-content -->
    </div> <!-- /form -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


</body>
</html>

Views/TAIKHOANs/Signup.cshtml
@model chothuexe1.Models.TAIKHOAN

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link href="~/fonts/css/styles.css" rel="stylesheet" />
</head>
<body>
    <div class="form">
        <div class="tab-content">

            <div id="signup">
                <h1>Đăng Ký Tài Khoản</h1>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="top-row">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="field-wrap">
                            <label>
                                Tên Đăng Nhập<span class="req">*</span>
                            </label>
                            @Html.EditorFor(model => model.TenDangNhap, new { htmlAttributes = new { @class = "form-control", required = "required", autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.TenDangNhap, "", new { @class = "text-danger" })
                        </div>

                        <div class="field-wrap">
                            <label>
                                Họ Và Tên<span class="req">*</span>
                            </label>
                            @Html.EditorFor(model => model.HoVaTen, new { htmlAttributes = new { @class = "form-control", required = "required", autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.HoVaTen, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="field-wrap">
                        <label for="cmnd">
                            Số Căn Cước Công Dân<span class="req">*</span>
                        </label>
                        @Html.EditorFor(model => model.CCCD, new { htmlAttributes = new { @class = "form-control", required = "required", autocomplete = "off", pattern = "[0-9]{12}" } })
                        @Html.ValidationMessageFor(model => model.CCCD, "", new { @class = "text-danger-error-message-exist" })
                    </div>

                    <div class="field-wrap">
                        <label>
                            Số Điện Thoại<span class="req">*</span>
                        </label>
                        @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control", required = "required", autocomplete = "off", pattern = "[0-9]{10}" } })
                        @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger-error-message-exist" })
                    </div>

                    <div class="field-wrap">
                        <label>
                            Email<span class="req">*</span>
                        </label>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", required = "required", autocomplete = "off", type = "email" } })
                    </div>

                    <div class="field-wrap">
                        <label>
                            Mật Khẩu<span class="req">*</span>
                        </label>
                        @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control", required = "required", autocomplete = "off", type = "password" } })
                    </div>

                    <div class="field-wrap">
                        <label>
                            Xác Nhận Mật Khẩu<span class="req">*</span>
                        </label>
                        <input type="password" required autocomplete="off" />
                    </div>

                    <button type="submit" class="button button-block">Đăng Ký Ngay</button>

                }
            </div>
                    <p>@Html.ActionLink("Bạn đã có tài khoản ?Đăng nhập", "Login", "TAIKHOANs")</p>
        </div><!-- tab-content -->
    </div> <!-- /form -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/fonts/js/scripts.js"></script>
</body>
</html>